push!(LOAD_PATH, dirname(@__FILE__))
@everywhere log(1.0) # Workaround for https://github.com/JuliaLang/julia/issues/18465
reload("Analysis")
Analysis.compute_permpval()
Analysis.compute_permpval_eachisi()
Analysis.compute_latency()
Analysis.compute_alignedinfoisi()
Analysis.compute_permpval_isiwin()
Analysis.compute_permpval_maintenance()
Analysis.compute_modulation_maintenance()
Analysis.compute_modulation_presentation()
Analysis.compute_maintenance_topstim_holdout()
Analysis.compute_maintenance_topstim_correct()
Analysis.compute_alignedinfoisi(pos1=true)
